import React from 'react';
import { Wrapper, Title, Container, Section, Row, StatTitle, StatValue, Header } from './elements';

class StatsSection extends React.Component<any> {
  render() {
    return (
      <Wrapper>
        <Header>
          <Title>Rating aspects</Title>
        </Header>
        <Container>
          <Section>
            <Row>
                <StatTitle>location</StatTitle>
                <StatValue>1</StatValue>
            </Row>
            <Row>
                <StatTitle>location</StatTitle>
                <StatValue>2</StatValue>
            </Row>
            <Row>
                <StatTitle>location</StatTitle>
                <StatValue>3</StatValue>
            </Row>
            <Row>
                <StatTitle>location</StatTitle>
                <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
          </Section>
          <Section>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
            <Row>
              <StatTitle>location</StatTitle>
              <StatValue>3</StatValue>
            </Row>
          </Section>
        </Container>
      </Wrapper>
    );
  }
}

export default StatsSection;
